services:
  neuron:
    image: emqx/neuronex:3.7
    container_name: neuron-ex
    extra_hosts:
      # - 'localhost:host-gateway'
      - 'host.docker.internal:host-gateway'
    ports:
      - '8085:8085'
